# Generated by Django 4.2.1 on 2023-06-01 01:44

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('panel', '0002_filledform'),
    ]

    operations = [
        migrations.AddField(
            model_name='filledform',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
